/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GapFramework { 'frameworkType' : string, 'details' : string }
export interface ResearchQuestion {
  'text' : string,
  'framework' : string,
  'rationale' : string,
}
export interface SearchSession {
  'id' : bigint,
  'selectedStudies' : Array<Study>,
  'createdAt' : bigint,
  'researchQuestions' : Array<ResearchQuestion>,
  'synthesisTable' : [] | [SynthesisTable],
  'broadArea' : string,
}
export interface Study {
  'id' : bigint,
  'doi' : string,
  'title' : string,
  'source' : string,
  'journal' : string,
  'year' : bigint,
  'gapFramework' : [] | [GapFramework],
  'volume' : string,
  'researchGaps' : string,
  'authors' : Array<string>,
  'abstract' : string,
  'pages' : string,
  'keyFindings' : string,
}
export interface SynthesisTable {
  'generatedAt' : bigint,
  'studies' : Array<Study>,
  'sessionId' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addResearchQuestion' : ActorMethod<[bigint, ResearchQuestion], undefined>,
  'addStudy' : ActorMethod<[bigint, Study], bigint>,
  'createSession' : ActorMethod<[string], bigint>,
  'deleteSession' : ActorMethod<[bigint], undefined>,
  'fetchPubMedArticles' : ActorMethod<[string], string>,
  'getAllSessions' : ActorMethod<[], Array<SearchSession>>,
  'getResearchQuestions' : ActorMethod<[bigint], Array<ResearchQuestion>>,
  'getSession' : ActorMethod<[bigint], [] | [SearchSession]>,
  'getStudies' : ActorMethod<[bigint], Array<Study>>,
  'getStudiesByFramework' : ActorMethod<[bigint, string], Array<Study>>,
  'getStudy' : ActorMethod<[bigint, bigint], [] | [Study]>,
  'getSynthesisTable' : ActorMethod<[bigint], [] | [SynthesisTable]>,
  'saveSynthesisTable' : ActorMethod<[bigint, Array<Study>], undefined>,
  'searchPubMed' : ActorMethod<[string], string>,
  'searchStudies' : ActorMethod<[bigint, string], Array<Study>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];