/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResearchQuestion = IDL.Record({
  'text' : IDL.Text,
  'framework' : IDL.Text,
  'rationale' : IDL.Text,
});
export const GapFramework = IDL.Record({
  'frameworkType' : IDL.Text,
  'details' : IDL.Text,
});
export const Study = IDL.Record({
  'id' : IDL.Nat,
  'doi' : IDL.Text,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'journal' : IDL.Text,
  'year' : IDL.Nat,
  'gapFramework' : IDL.Opt(GapFramework),
  'volume' : IDL.Text,
  'researchGaps' : IDL.Text,
  'authors' : IDL.Vec(IDL.Text),
  'abstract' : IDL.Text,
  'pages' : IDL.Text,
  'keyFindings' : IDL.Text,
});
export const SynthesisTable = IDL.Record({
  'generatedAt' : IDL.Int,
  'studies' : IDL.Vec(Study),
  'sessionId' : IDL.Nat,
});
export const SearchSession = IDL.Record({
  'id' : IDL.Nat,
  'selectedStudies' : IDL.Vec(Study),
  'createdAt' : IDL.Int,
  'researchQuestions' : IDL.Vec(ResearchQuestion),
  'synthesisTable' : IDL.Opt(SynthesisTable),
  'broadArea' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addResearchQuestion' : IDL.Func([IDL.Nat, ResearchQuestion], [], []),
  'addStudy' : IDL.Func([IDL.Nat, Study], [IDL.Nat], []),
  'createSession' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteSession' : IDL.Func([IDL.Nat], [], []),
  'fetchPubMedArticles' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(SearchSession)], ['query']),
  'getResearchQuestions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ResearchQuestion)],
      ['query'],
    ),
  'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(SearchSession)], ['query']),
  'getStudies' : IDL.Func([IDL.Nat], [IDL.Vec(Study)], ['query']),
  'getStudiesByFramework' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Study)],
      ['query'],
    ),
  'getStudy' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Study)], ['query']),
  'getSynthesisTable' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SynthesisTable)],
      ['query'],
    ),
  'saveSynthesisTable' : IDL.Func([IDL.Nat, IDL.Vec(Study)], [], []),
  'searchPubMed' : IDL.Func([IDL.Text], [IDL.Text], []),
  'searchStudies' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(Study)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResearchQuestion = IDL.Record({
    'text' : IDL.Text,
    'framework' : IDL.Text,
    'rationale' : IDL.Text,
  });
  const GapFramework = IDL.Record({
    'frameworkType' : IDL.Text,
    'details' : IDL.Text,
  });
  const Study = IDL.Record({
    'id' : IDL.Nat,
    'doi' : IDL.Text,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'journal' : IDL.Text,
    'year' : IDL.Nat,
    'gapFramework' : IDL.Opt(GapFramework),
    'volume' : IDL.Text,
    'researchGaps' : IDL.Text,
    'authors' : IDL.Vec(IDL.Text),
    'abstract' : IDL.Text,
    'pages' : IDL.Text,
    'keyFindings' : IDL.Text,
  });
  const SynthesisTable = IDL.Record({
    'generatedAt' : IDL.Int,
    'studies' : IDL.Vec(Study),
    'sessionId' : IDL.Nat,
  });
  const SearchSession = IDL.Record({
    'id' : IDL.Nat,
    'selectedStudies' : IDL.Vec(Study),
    'createdAt' : IDL.Int,
    'researchQuestions' : IDL.Vec(ResearchQuestion),
    'synthesisTable' : IDL.Opt(SynthesisTable),
    'broadArea' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addResearchQuestion' : IDL.Func([IDL.Nat, ResearchQuestion], [], []),
    'addStudy' : IDL.Func([IDL.Nat, Study], [IDL.Nat], []),
    'createSession' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteSession' : IDL.Func([IDL.Nat], [], []),
    'fetchPubMedArticles' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(SearchSession)], ['query']),
    'getResearchQuestions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ResearchQuestion)],
        ['query'],
      ),
    'getSession' : IDL.Func([IDL.Nat], [IDL.Opt(SearchSession)], ['query']),
    'getStudies' : IDL.Func([IDL.Nat], [IDL.Vec(Study)], ['query']),
    'getStudiesByFramework' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Study)],
        ['query'],
      ),
    'getStudy' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Study)], ['query']),
    'getSynthesisTable' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SynthesisTable)],
        ['query'],
      ),
    'saveSynthesisTable' : IDL.Func([IDL.Nat, IDL.Vec(Study)], [], []),
    'searchPubMed' : IDL.Func([IDL.Text], [IDL.Text], []),
    'searchStudies' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Study)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };